# WEAVIATE_DOCS_INDEX_NAME = "LangChain_Combined_Docs_OpenAI_text_embedding_3_small"
# WEAVIATE_DOCS_INDEX_NAME = "Canada_Water"
# WEAVIATE_DOCS_INDEX_NAME = "Anything_project"
WEAVIATE_DOCS_INDEX_NAME = "Trinity_Island"
# 04.Trinity-Island"
