name: RAG backend
on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Fix up git URLs
              run: echo -e '[url "https://github.com/"]\n  insteadOf = "git://github.com/"' >> ~/.gitconfig

            - name: checkout repo
              uses: actions/checkout@v2

            - name: Login to Docker HUB
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Build and Push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:dev
                  # cache-from: type=registry,ref=user/app:latest
                  # cache-to: type=inline

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
